// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdiqmwnpviedgpnobzic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkaXFtd25wdmllZGdwbm9iemljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDAyNTcsImV4cCI6MjA1OTk3NjI1N30.CoZosixmsHCFre99wdhfsNBhphYVYZuUBDeBwafuhQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);